const test=require('node:test'),assert=require('node:assert/strict');
const {ArcadeGames}=require('../src/arcade-games');
const {buildAnalyticsReport}=require('../src/analytics');
const now=new Date('2026-10-05T18:00:00Z');
function fixture(){let time=+now-600000;const events=[];const game=new ArcadeGames({now:()=>time,random:()=>0,schedule:()=>0,cancel:()=>{},recordEvent:e=>events.push(e)});return {game,events,tick:()=>time+=20000};}
const chat=(text='1',platform='twitch',id='a')=>({text,platform,user:{id,username:id}});
test('only accepted votes, resolved rounds and one stop are recorded',()=>{const {game:g,events,tick}=fixture();g.start('boss');g.handleChatEvent(chat());g.handleChatEvent(chat('2'));g.handleChatEvent(chat('hello','youtube','b'));tick();g.resolve();g.stop();g.stop();assert.deepEqual(events.map(e=>e.eventType),['game_started','vote','round_completed','game_stopped']);assert.equal(events[1].metadata.action,'attack');assert.equal(events[2].metadata.combat.action,'attack');assert.equal(events[3].metadata.durationMs,20000);assert.equal(events[0].metadata.boss,'pumpkin');});
test('six games reconcile across totals, activity, sessions and platform filters',()=>{const {game:g,events,tick}=fixture();for(const id of ['boss','escape','higher','split','number','snacks']){g.start(id);g.handleChatEvent(chat());g.handleChatEvent(chat('2','youtube','b'));tick();g.resolve();g.stop();}const r=buildAnalyticsReport({events,now});assert.equal(r.tools.arcade.plays,6);assert.equal(r.tools.arcade.uniquePlayers,2);assert.equal(r.tools.arcade.repeatPlayers,2);assert.equal(r.tools.arcade.acceptedVotes,12);assert.deepEqual(Object.values(r.reconciliation),[12,12,12,12]);assert.equal(r.sessions[0].arcadeVotes,12);assert.equal(r.timeline.reduce((n,d)=>n+d.hillVotes,0),0);const f=buildAnalyticsReport({events,now,platform:'twitch',activityTool:'chat_games'});assert.equal(f.tools.arcade.plays,6);assert.equal(f.tools.arcade.acceptedVotes,6);assert.equal(f.tools.arcade.uniquePlayers,1);assert.equal(f.activityPagination.tool,'chat_games');assert.ok(f.activity.every(e=>e.tool==='chat_games'));assert.deepEqual(Object.values(f.reconciliation),[6,6,6,6]);});
test('legacy details remain unknown and test activity is excluded',()=>{const events=[{timestamp:'2026-10-05T17:00:00Z',tool:'chat_games',eventType:'game_completed',correlationId:'legacy',metadata:{game:'boss',round:8,votes:12,result:'Out of turns'}},{timestamp:'2026-10-05T17:01:00Z',tool:'chat_games',eventType:'vote',correlationId:'test',platform:'twitch',userId:'test',metadata:{game:'higher',schemaVersion:2,isTest:true}}];const r=buildAnalyticsReport({events,now});assert.equal(r.tools.arcade.legacyGames,1);assert.equal(r.tools.arcade.history[0].players,null);assert.equal(r.tools.arcade.history[0].outcome,null);assert.equal(r.tools.arcade.games.find(g=>g.id==='boss').recordedVotes,12);assert.equal(r.overview.interactions,0);assert.equal(r.activity.length,1);assert.equal(r.tools.arcade.history[0].durationSeconds,null);});
test('winning final round is counted once; stopping after completion is not an abandonment',()=>{const {game:g,events,tick}=fixture();g.start('boss');g.bossHp=1;g.handleChatEvent(chat());tick();g.resolve();g.stop();const r=buildAnalyticsReport({events,now});assert.deepEqual(events.map(e=>e.eventType),['game_started','vote','game_completed']);assert.equal(r.tools.arcade.bosses[0].wins,1);assert.equal(r.tools.arcade.bosses[0].winRate,100);assert.equal(r.tools.arcade.actions[0].turns,1);assert.equal(r.tools.arcade.history[0].rounds,1);assert.equal(r.tools.arcade.history[0].durationSeconds,20);});
test('late answers and a game with no votes do not inflate engagement',()=>{const {game:g,events,tick}=fixture();g.start('higher');tick();tick();g.handleChatEvent(chat());g.stop();const r=buildAnalyticsReport({events,now});assert.equal(r.tools.arcade.plays,1);assert.equal(r.tools.arcade.uniquePlayers,0);assert.equal(r.tools.arcade.acceptedVotes,0);assert.equal(r.overview.interactions,0);assert.ok(events.some(e=>e.eventType==='round_completed'));});
test('range boundaries keep known duration without inventing missing starts or votes',()=>{const events=[{timestamp:'2026-09-01T17:00:00Z',tool:'chat_games',eventType:'game_started',correlationId:'old',metadata:{schemaVersion:2,game:'boss',boss:'frost'}},{timestamp:'2026-10-05T17:00:00Z',tool:'chat_games',eventType:'game_completed',correlationId:'old',metadata:{schemaVersion:2,game:'boss',boss:'frost',round:12,votes:0,outcome:'loss',durationMs:720000}}];const r=buildAnalyticsReport({events,now,range:'7d'});assert.equal(r.tools.arcade.history[0].startedAt,null);assert.equal(r.tools.arcade.history[0].durationSeconds,720);assert.equal(r.tools.arcade.bosses[1].losses,1);assert.equal(r.tools.arcade.bosses[1].averageTurns,12);assert.equal(r.tools.arcade.games.find(g=>g.id==='boss').started,0);});
