const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs'),os=require('node:os'),path=require('node:path');
process.env.DATA_DIR=fs.mkdtempSync(path.join(os.tmpdir(),'stream-mod-access-'));
process.env.APP_MODE='cloud';
process.env.PUBLIC_BASE_URL='https://stream.example.test';
process.env.ADMIN_PASSWORD='owner-password-for-isolated-tests';
process.env.SESSION_SECRET='test-session-secret-'.repeat(4);
process.env.BRIDGE_TOKEN='test-bridge-token-'.repeat(4);
const {app}=require('../src/admin');
const access=require('../src/moderator-access');
const {quizGame}=require('../src/quiz-game');
const {db}=require('../src/db');
test('games-only access is enforced across routes, handoff, expiry and revocation',async t=>{
 const server=app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));
 t.after(()=>{quizGame.stop();server.closeAllConnections();server.close();db.close();});
 const base=`http://127.0.0.1:${server.address().port}`;
 const call=(url,{cookie,method='GET',body,origin='https://stream.example.test',version}={})=>fetch(base+url,{method,redirect:'manual',headers:{accept:'application/json',...(cookie?{cookie}:{}),...(method!=='GET'?{'Content-Type':'application/json',Origin:origin}:{}),...(version?{'X-Game-Version':version}:{})},...(body!==undefined?{body:JSON.stringify(body)}:{})});
 async function login(username,password){const res=await call('/admin/login',{method:'POST',body:{username,password}});assert.equal(res.status,302);return res.headers.get('set-cookie').split(';')[0];}
 assert.equal((await call('/admin/games')).status,401);
 const owner=await login('owner',process.env.ADMIN_PASSWORD);
 const created=await call('/admin/moderators/create',{cookie:owner,method:'POST',body:{username:'helper',password:'helper-password-long'}});
 assert.equal(created.status,200);const {user}=await created.json();
 const mod=await login('helper','helper-password-long');
 for(const url of ['/admin/games','/admin/quiz','/admin/king-of-the-hill','/admin/games/session','/admin/games/connections','/admin/quiz/state'])assert.equal((await call(url,{cookie:mod})).status,200,url);
 for(const url of ['/admin','/admin/config','/admin/analytics','/admin/analytics/summary','/admin/analytics/activity','/admin/requests','/admin/spotify/connect','/admin/polaroid','/admin/moderators','/admin/performance','/admin/connections','/admin/quiz/preview','/admin/quiz/test/catalog'])assert.equal((await call(url,{cookie:mod})).status,403,url);
 for(const url of ['/admin/save','/admin/override','/admin/override/remove','/admin/spotify/disconnect','/admin/polaroid/redeem','/admin/moderators/handoff','/admin/settings/song-requests','/admin/quiz/test'])assert.equal((await call(url,{cookie:mod,method:'POST',body:{}})).status,403,url);
 assert.equal((await call('/admin/requests/1',{cookie:mod,method:'DELETE'})).status,403);
 assert.equal((await call('/admin/quiz/open',{cookie:mod,method:'POST',body:{}})).status,403);
 assert.equal((await call('/admin/moderators/handoff',{cookie:owner,method:'POST',body:{enabled:true,minutes:30}})).status,200);
 assert.equal((await call('/admin/quiz/open',{cookie:mod,method:'POST',body:{},origin:'https://evil.example'})).status,403);
 assert.equal((await call('/admin/quiz/open',{cookie:mod,method:'POST',body:{}})).status,409);
 const version=quizGame.getState().controlVersion;
 const opened=await call('/admin/quiz/open',{cookie:mod,method:'POST',body:{questionCount:1,answerSeconds:5},version});assert.equal(opened.status,200);
 assert.equal((await call('/admin/quiz/stop',{cookie:mod,method:'POST',body:{},version})).status,409);
 const fresh=quizGame.getState().controlVersion;
 assert.equal((await call('/admin/quiz/stop',{cookie:mod,method:'POST',body:{},version:fresh})).status,200);
 await call('/admin/moderators/handoff',{cookie:owner,method:'POST',body:{enabled:false,minutes:30}});
 assert.equal((await call('/admin/king-of-the-hill/start',{cookie:mod,method:'POST',body:{},version:'old'})).status,403);
 assert.equal((await call('/quiz/state')).status,200);
 assert.equal((await call('/assets/admin.html')).status,404);
 assert.equal((await call('/admin/moderators/state',{cookie:owner})).status,200);
 await call(`/admin/moderators/${user.id}/revoke`,{cookie:owner,method:'POST',body:{}});
 assert.equal((await call('/admin/games',{cookie:mod})).status,401);
 const expired=access.issue({id:'owner',role:'owner'},Date.now()-13*3600000);
 assert.equal((await call('/admin/games',{cookie:`stream_control_session=${expired}`})).status,401);
 await call('/admin/logout',{cookie:owner,method:'POST',body:{}});
 assert.equal((await call('/admin/games',{cookie:owner})).status,401);
});
