const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
process.env.APP_MODE='cloud';process.env.DATA_DIR=fs.mkdtempSync(path.join(os.tmpdir(),'october-access-'));process.env.PUBLIC_BASE_URL='https://stream.example.test';process.env.ADMIN_PASSWORD='test-owner-password-only';process.env.SESSION_SECRET='test-secret-'.repeat(8);process.env.BRIDGE_TOKEN='test-bridge-'.repeat(8);
const {app}=require('../src/admin'),access=require('../src/moderator-access');const {arcadeGames}=require('../src/arcade-games');const {db,getConfigValue}=require('../src/db');
test('persistent moderator switch, owner-only tests/device keys, device revocation and safe public overlays',async t=>{
 const server=app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));t.after(()=>{arcadeGames.stop();server.closeAllConnections();server.close();db.close();});const base=`http://127.0.0.1:${server.address().port}`;
 async function call(url,body,cookie,token){return fetch(base+url,{method:body===undefined?'GET':'POST',redirect:'manual',headers:{accept:'application/json',...(cookie?{cookie}:{}),...(token?{Authorization:'Bearer '+token}:{}),...(body===undefined?{}:{'Content-Type':'application/json',Origin:'https://stream.example.test'})},...(body===undefined?{}:{body:JSON.stringify(body)})});}
 const owner=(await call('/admin/login',{username:'owner',password:process.env.ADMIN_PASSWORD})).headers.get('set-cookie').split(';')[0];await access.create('helper','test-moderator-password');const mod=(await call('/admin/login',{username:'helper',password:'test-moderator-password'})).headers.get('set-cookie').split(';')[0];
 assert.equal((await call('/admin/games/quick')).status,401);assert.equal((await call('/admin/games/quick',undefined,mod)).status,200);
 for(const route of ['/admin/games/device-token','/admin/games/device-token/revoke','/admin/moderators/handoff','/admin/polaroid/redeem'])assert.equal((await call(route,{},mod)).status,403,route);
 assert.equal((await call('/admin/games/action',{action:'launch',game:'snacks'},mod)).status,403);
 await call('/admin/moderators/handoff',{enabled:true},owner);assert.equal(access.handoff(Date.now()+365*86400000).enabled,true);assert.equal(getConfigValue('games_control_persistent').expiresAt,null);
 assert.equal((await call('/admin/games/action',{action:'launch',game:'snacks'},mod)).status,200);assert.equal((await call('/admin/games/action',{action:'launch',game:'quiz'},owner)).status,409);
 await call('/admin/moderators/handoff',{enabled:false},owner);assert.equal((await call('/admin/games/action',{action:'stop',game:'snacks'},mod)).status,403);assert.equal(arcadeGames.phase,'question');await call('/admin/games/action',{action:'stop',game:'snacks'},owner);
 const {token}=await(await call('/admin/games/device-token',{},owner)).json();assert.equal((await call('/api/games/action',{action:'launch',game:'snacks'})).status,401);assert.equal((await call('/api/games/action',{action:'launch',game:'snacks'},null,token)).status,200);await call('/api/games/action',{action:'stop',game:'snacks'},null,token);await call('/admin/games/device-token/revoke',{},owner);assert.equal((await call('/api/games/action',{action:'launch',game:'snacks'},null,token)).status,401);
 for(const url of ['/chat-games','/quiz?theme=halloween','/king-of-the-hill?theme=ghost','/assets/seasonal-theme.css'])assert.equal((await call(url)).status,200,url);assert.equal((await call('/assets/games-quick.html')).status,404);
});
